#ifndef CONSTANTS_HEADER
#define CONSTANTS_HEADER

#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 1000
#define WINDOW_TITLE "Raymarching | Eclips-Coding"

#define RENDER_FPS 30
#define RENDER_FPS_X 10
#define RENDER_FPS_Y 10

#define DEFAULT_RADIUS 10
#define DEFAULT_LINE_THICKNESS 1

#define WORLD_SIZE 20
#define WORLD_MIN_RADIUS 10
#define WORLD_MAX_RADIUS 100

#define MINIMUM_DISTANCE 2

#define POINT_RADIUS 2

#endif